apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- virtual-service.yaml
- authorization-policy.yaml
- destination-rule.yaml
namespace: kubeflow
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app


replacements:
- source:
    kind: Service
    name: service
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: VirtualService
    fieldPaths:
    - spec.http.0.route.0.destination.host
    options:
      delimiter: "."
      index: 1
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.JWA_CLUSTER_DOMAIN
  targets:
  - select:
      kind: VirtualService
    fieldPaths:
    - spec.http.0.route.0.destination.host
    options:
      delimiter: "."
      index: 3
