apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-home-pvc
  labels:
    notebooks.kubeflow.org/can-mount: "true"
    notebooks.kubeflow.org/can-update: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi