apiVersion: v1
kind: Secret
metadata:
  name: workspace-secret
  labels:
    notebooks.kubeflow.org/can-mount: "true"
    notebooks.kubeflow.org/can-update: "true"
type: Opaque
data:
  key1: dmFsdWUx
  key2: dmFsdWUy