exclude: '(^|.*/)upstream/.*'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: detect-private-key
- repo: https://github.com/adrienverge/yamllint
  rev: v1.38.0
  hooks:
  - id: yamllint
    files: ^(common|example|hack|tests|\.github)/.*\.ya?ml$
    exclude: .*upstream.*
    args: [--config-file=.yamllint.yaml]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
    files: ^.*\.sh$
    exclude: (^applications/.*|.*upstream.*)
- repo: https://github.com/psf/black
  rev: 26.3.1
  hooks:
  - id: black
    files: ^(common|example)/.*\.py$
    exclude: .*upstream.*
