apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-workspaces-admin
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-workspaces-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-workspaces-edit
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-workspaces-admin: "true"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-workspaces-edit: "true"
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - workspaces
  - workspaces/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-workspaces-view
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-workspaces-edit: "true"
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - workspaces
  - workspaces/status
  verbs:
  - get
  - list
  - watch
