apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-install-config
data:
  defaultSecurityContextRunAsUser: "1000"
  defaultSecurityContextRunAsGroup: "1000"
  defaultSecurityContextRunAsNonRoot: "true"
