{{- if and .Values.crds.enabled (eq (default "platform-database" .Values.scenario) "platform-database") }}
{{ include "kubeflow-pipelines.payload" (dict "root" . "path" "manifests/platform-database-crds.yaml") }}
{{- end }}
