apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kepler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kepler-role
subjects:
- kind: ServiceAccount
  name: kepler-sa
  namespace: kubeflow-monitoring-system
