apiVersion: v1
kind: Service
metadata:
  name: kepler
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
spec:
  ports:
  - name: http
    port: 9102
    targetPort: 9102
  selector:
    app.kubernetes.io/name: kepler
