#!/bin/bash
kubectl create ns auth

./gencert.sh

kubectl create secret tls auth.krishnadurai.com.tls --cert=ssl/cert.pem --key=ssl/key.pem -n auth


# CA ( ca.pem generated by gencert.sh) configmap
kubectl create -f ca-cm.yml
# Login App configuration
kubectl create -f loginapp-cm.yml
# Login App service
kubectl create -f loginapp-ing-svc.yml
# Login App Deployment
kubectl create -f loginapp-deploy.yml
