apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namePrefix: tensorboards-web-app-
namespace: kubeflow
images:
- name: ghcr.io/kubeflow/kubeflow/tensorboards-web-app
  newName: ghcr.io/kubeflow/kubeflow/tensorboards-web-app
  newTag: v1.10.0
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
configMapGenerator:
- envs:
  - params.env
  name: parameters
labels:
- includeSelectors: true
  pairs:
    app: tensorboards-web-app
    kustomize.component: tensorboards-web-app
replacements:
- source:
    fieldPath: data.TWA_USERID_HEADER
    kind: ConfigMap
    name: parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.1.value
    select:
      group: apps
      kind: Deployment
      name: deployment
      version: v1
- source:
    fieldPath: data.TWA_USERID_PREFIX
    kind: ConfigMap
    name: parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.2.value
    select:
      group: apps
      kind: Deployment
      name: deployment
      version: v1
- source:
    fieldPath: data.TWA_PREFIX
    kind: ConfigMap
    name: parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.0.value
    select:
      group: apps
      kind: Deployment
      name: deployment
      version: v1
- source:
    fieldPath: data.TWA_APP_SECURE_COOKIES
    kind: ConfigMap
    name: parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.3.value
    select:
      group: apps
      kind: Deployment
      name: deployment
      version: v1
- source:
    fieldPath: data.TWA_APP_ENABLE_METRICS
    kind: ConfigMap
    name: parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.4.value
    select:
      group: apps
      kind: Deployment
      name: deployment
      version: v1