apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- behavior: replace
  files:
  - sources.yaml=sources.yaml
  - mcp-servers.yaml=mcp-servers.yaml
  name: model-catalog-sources
  options:
    disableNameSuffixHash: true
