apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# --> DANGER: Workspaces (Notebooks v2) is still pre-GA <--
#
# !!! DO NOT DEPLOY THIS TO A PRODUCTION CLUSTER !!!
#
# See this for the current status: https://www.kubeflow.org/docs/components/notebooks/notebooks-v2-pre-ga-banner
resources:
- ../../../upstream/frontend/overlays/istio

patches:
- patch: |
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kubeflow-workspaces
