apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- allow-webhook-apiserver.yaml
- default-allow-same-namespace.yaml

patches:
- path: namespace-patch.yaml
- path: patches/request-reply-security-context.yaml
