#!/usr/bin/env python3
"""Shared engine that turns a Kustomize build into Helm chart payloads.

A component supplies a GeneratorConfiguration describing where to build from,
where to write, which resources its chart renders by hand, and which embedded
documents to extract. Everything else - Kubernetes identity validation,
duplicate detection, custom resource definition retention, deterministic
rendering and atomic replacement - is component independent and lives here.

Helm loads the generated payloads with .Files.Get, which does not send content
through the template renderer, so Go template delimiters that upstream manifests
legitimately contain survive verbatim.
"""

import copy
import io
import os
import re
import shutil
import stat
import subprocess
import tempfile
import uuid

from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path

from ruamel.yaml import YAML

CRD_KIND = "CustomResourceDefinition"
CRD_RETENTION_ANNOTATION = "helm.sh/resource-policy"
KUSTOMIZE_HASH_PATTERN = r"[a-z0-9]{10}"
DOCUMENTS_DIRECTORY = "documents"
DEFAULT_DIRECTORY_MODE = 0o755


@dataclass(frozen=True)
class GeneratorConfiguration:
    """Everything that differs between components."""

    component_name: str
    kustomize_path: Path
    output_path: Path
    generator_script: str
    synchronize_script: str
    crds_payload_filename: str = "platform-crds.yaml"
    # When set, every custom resource definition is written to its own file,
    # <directory>/<definition name>.yaml, instead of crds_payload_filename.
    # Helm refuses to load any chart file above 5 MiB, and one component's
    # definitions together can exceed that.
    crds_payload_directory: str = ""
    resources_payload_filename: str = "platform-resources.yaml"
    # (kind, name or name prefix, name_is_prefix)
    hand_written_resources: tuple = ()
    # (kind, name or name prefix, name_is_prefix, data key, output filename)
    extracted_documents: tuple = ()
    # (kind, name): rendered by Kustomize but owned by another Helm release, so
    # left out of every payload and rendered by no template either.
    excluded_resources: tuple = ()

    def generated_header(self):
        return (
            f"# Code generated by {self.generator_script}. DO NOT EDIT.\n"
            f"# Source: kustomize build {self.kustomize_path}\n"
            f"# Regenerate with: KUBEFLOW_SYNCHRONIZE_NO_COMMIT=true "
            f"./{self.synchronize_script}\n"
        )


def resource_identity(resource):
    if not isinstance(resource, Mapping):
        raise ValueError("resource identity requires a YAML mapping")

    api_version = resource.get("apiVersion")
    kind = resource.get("kind")
    metadata = resource.get("metadata")
    if not isinstance(api_version, str) or not api_version:
        raise ValueError("resource identity is missing apiVersion")
    if not isinstance(kind, str) or not kind:
        raise ValueError("resource identity is missing kind")
    if not isinstance(metadata, Mapping):
        raise ValueError("resource identity is missing metadata")

    name = metadata.get("name")
    namespace = metadata.get("namespace", "")
    if not isinstance(name, str) or not name:
        raise ValueError("resource identity is missing metadata.name")
    if not isinstance(namespace, str):
        raise ValueError("resource identity has a non-string metadata.namespace")

    return api_version, kind, namespace, name


def kubernetes_object_identity(resource):
    api_version, kind, namespace, name = resource_identity(resource)
    api_group = api_version.split("/", maxsplit=1)[0] if "/" in api_version else ""
    return api_group, kind, namespace, name


def matches_selector(resource, kind, name, name_is_prefix):
    _, resource_kind, _, resource_name = resource_identity(resource)
    if resource_kind != kind:
        return False
    if not name_is_prefix:
        return resource_name == name
    return (
        re.fullmatch(re.escape(name) + KUSTOMIZE_HASH_PATTERN, resource_name)
        is not None
    )


def parse_resources(rendered_yaml):
    yaml = YAML()
    yaml.allow_duplicate_keys = False
    resources = []
    for document_number, resource in enumerate(yaml.load_all(rendered_yaml), start=1):
        if resource is None:
            continue
        if not isinstance(resource, Mapping):
            raise ValueError(
                f"YAML document {document_number} is not a Kubernetes resource mapping"
            )
        resources.append(resource)
    if not resources:
        raise ValueError("Kustomize rendered no Kubernetes resources")
    return resources


def add_crd_retention(resource):
    retained_resource = copy.deepcopy(resource)
    metadata = retained_resource["metadata"]
    annotations = metadata.get("annotations")
    if annotations is None:
        annotations = {}
        metadata["annotations"] = annotations
    if not isinstance(annotations, Mapping):
        raise ValueError(
            f"CRD {resource_identity(resource)} has non-mapping metadata.annotations"
        )
    annotations[CRD_RETENTION_ANNOTATION] = "keep"
    return retained_resource


def render_payload(resources, header):
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.explicit_start = True
    yaml.width = 4096
    stream = io.StringIO()
    yaml.dump_all(resources, stream)
    return header + stream.getvalue()


def extract_documents(resource, configuration):
    """Return the embedded documents this resource contributes."""
    documents = {}
    for (
        kind,
        name,
        name_is_prefix,
        data_key,
        filename,
    ) in configuration.extracted_documents:
        if not matches_selector(resource, kind, name, name_is_prefix):
            continue
        data = resource.get("data")
        if not isinstance(data, Mapping) or data_key not in data:
            raise ValueError(
                f"resource {resource_identity(resource)} is missing "
                f"data key {data_key!r} required for {filename}"
            )
        value = data[data_key]
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"resource {resource_identity(resource)} has an empty "
                f"data key {data_key!r} required for {filename}"
            )
        documents[f"{DOCUMENTS_DIRECTORY}/{filename}"] = value.rstrip("\n") + "\n"
    return documents


def generate_payload_contents(resources, configuration):
    crd_resources = []
    payload_resources = []
    documents = {}
    object_identities = set()
    matched_selectors = {}
    matched_exclusions = set()

    for resource in resources:
        identity = resource_identity(resource)
        object_identity = kubernetes_object_identity(resource)
        if object_identity in object_identities:
            raise ValueError(f"duplicate resource identity: {identity}")
        object_identities.add(object_identity)

        exclusion = (identity[1], identity[3])
        if exclusion in configuration.excluded_resources:
            matched_exclusions.add(exclusion)
            continue

        hand_written_selector = next(
            (
                selector
                for selector in configuration.hand_written_resources
                if matches_selector(resource, *selector)
            ),
            None,
        )
        if hand_written_selector is not None:
            if hand_written_selector in matched_selectors:
                raise ValueError(
                    f"resource {identity} matches hand-written selector "
                    f"{hand_written_selector} already matched by "
                    f"{matched_selectors[hand_written_selector]}"
                )
            matched_selectors[hand_written_selector] = identity
            documents.update(extract_documents(resource, configuration))
            continue

        if resource["kind"] == CRD_KIND:
            crd_resources.append(add_crd_retention(resource))
        else:
            payload_resources.append(copy.deepcopy(resource))

    unmatched_selectors = [
        selector
        for selector in configuration.hand_written_resources
        if selector not in matched_selectors
    ]
    if unmatched_selectors:
        raise ValueError(
            "hand-written resources are no longer rendered by Kustomize; "
            "their templates are orphaned: "
            + ", ".join(f"{kind}/{name}" for kind, name, _ in unmatched_selectors)
        )

    stale_exclusions = [
        exclusion
        for exclusion in configuration.excluded_resources
        if exclusion not in matched_exclusions
    ]
    if stale_exclusions:
        raise ValueError(
            "excluded resources are no longer rendered by Kustomize; "
            "the exclusions are stale: "
            + ", ".join(f"{kind}/{name}" for kind, name in stale_exclusions)
        )

    missing_documents = [
        f"{DOCUMENTS_DIRECTORY}/{filename}"
        for *_, filename in configuration.extracted_documents
        if f"{DOCUMENTS_DIRECTORY}/{filename}" not in documents
    ]
    if missing_documents:
        raise ValueError(
            "required embedded documents were not extracted: "
            + ", ".join(missing_documents)
        )

    if configuration.crds_payload_directory:
        crds_payload_name = configuration.crds_payload_directory + "/"
        crd_payloads = [
            (
                f"{configuration.crds_payload_directory}/"
                f"{resource_identity(resource)[3]}.yaml",
                [resource],
            )
            for resource in crd_resources
        ]
    else:
        crds_payload_name = configuration.crds_payload_filename
        crd_payloads = [(configuration.crds_payload_filename, crd_resources)]
    payloads = (
        *crd_payloads,
        (configuration.resources_payload_filename, payload_resources),
    )
    empty_payloads = [filename for filename, entries in payloads if not entries]
    if not crd_resources:
        empty_payloads.insert(0, crds_payload_name)
    if empty_payloads:
        raise ValueError(
            "required generated payloads are empty: " + ", ".join(empty_payloads)
        )

    header = configuration.generated_header()
    contents = {
        filename: render_payload(entries, header) for filename, entries in payloads
    }
    contents.update(documents)
    return contents


def write_payloads_atomically(output_directory, payloads):
    """Replace the output directory in one step, preserving its mode.

    tempfile.mkdtemp creates the staging directory as 0700. Moving it into place
    without restoring the mode would leave the generated payloads unreadable to
    any other user or containerized packaging step, and Git does not record
    directory modes, so a fresh checkout would hide the problem.
    """
    output_directory = Path(output_directory)
    output_directory.parent.mkdir(parents=True, exist_ok=True)
    if output_directory.exists():
        directory_mode = stat.S_IMODE(output_directory.stat().st_mode)
    else:
        directory_mode = DEFAULT_DIRECTORY_MODE
    staging_directory = Path(
        tempfile.mkdtemp(
            prefix=f".{output_directory.name}.new-",
            dir=output_directory.parent,
        )
    )
    backup_directory = output_directory.parent / (
        f".{output_directory.name}.old-{uuid.uuid4().hex}"
    )
    previous_directory_moved = False

    try:
        for filename, contents in payloads.items():
            relative_path = Path(filename)
            if relative_path.is_absolute() or ".." in relative_path.parts:
                raise ValueError(f"payload filename must be relative: {filename}")
            if len(relative_path.parts) > 2:
                raise ValueError(
                    f"payload filename must not nest more than one directory: "
                    f"{filename}"
                )
            if not contents.strip():
                raise ValueError(f"generated payload is empty: {filename}")
            destination = staging_directory / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(contents, encoding="utf-8", newline="\n")

        for directory in [staging_directory, *staging_directory.iterdir()]:
            if directory.is_dir():
                os.chmod(directory, directory_mode)

        if output_directory.exists():
            os.replace(output_directory, backup_directory)
            previous_directory_moved = True

        try:
            os.replace(staging_directory, output_directory)
        except Exception:
            if previous_directory_moved:
                os.replace(backup_directory, output_directory)
                previous_directory_moved = False
            raise

        if previous_directory_moved:
            shutil.rmtree(backup_directory)
            previous_directory_moved = False
    finally:
        if staging_directory.exists():
            shutil.rmtree(staging_directory)
        if previous_directory_moved and backup_directory.exists():
            if not output_directory.exists():
                os.replace(backup_directory, output_directory)


def generate_manifests(repository_root, configuration):
    repository_root = Path(repository_root).resolve()
    result = subprocess.run(
        ["kustomize", "build", str(configuration.kustomize_path)],
        cwd=repository_root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"{configuration.component_name} Kustomize build failed:\n"
            + result.stderr.rstrip()
        )

    resources = parse_resources(result.stdout)
    payloads = generate_payload_contents(resources, configuration)
    write_payloads_atomically(repository_root / configuration.output_path, payloads)
    return len(resources), tuple(payloads)
