#!/usr/bin/env bash
# This script helps to create a PR to update the unified Istio manifests
SCRIPT_DIRECTORY=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIRECTORY}/library.sh"
setup_error_handling
COMPONENT_NAME="istio"
REPOSITORY_NAME="istio/istio"
COMMIT="1.31.0"
PREVIOUS_COMMIT="1.30.3"
SOURCE_DIRECTORY=${SOURCE_DIRECTORY:=/tmp/kubeflow-${COMPONENT_NAME}}
BRANCH_NAME=${BRANCH_NAME:=synchronize-${COMPONENT_NAME}-manifests-${COMMIT?}}
MANIFESTS_DIRECTORY=$(dirname $SCRIPT_DIRECTORY)
ISTIO_DIRECTORY=$MANIFESTS_DIRECTORY/common/${COMPONENT_NAME}
HELM_MANIFESTS_DIRECTORY="$ISTIO_DIRECTORY/helm/manifests"
# istioctl writes these intermediate dumps into the component directory. Remove
# them on any exit so a failed run does not leave them in the working tree.
trap 'rm -f "$ISTIO_DIRECTORY/dump.yaml" "$ISTIO_DIRECTORY/dump-ztunnel.yaml"' EXIT
create_branch "$BRANCH_NAME"
mkdir -p "$SOURCE_DIRECTORY"
mkdir -p "$HELM_MANIFESTS_DIRECTORY"
cd "$SOURCE_DIRECTORY"
if [ ! -d "istio-${COMMIT}" ]; then
    wget "https://github.com/${REPOSITORY_NAME}/releases/download/${COMMIT}/istio-${COMMIT}-linux-amd64.tar.gz"
    tar xvfz istio-${COMMIT}-linux-amd64.tar.gz
fi
ISTIOCTL="${SOURCE_DIRECTORY}/istio-${COMMIT}/bin/istioctl"
cd "$ISTIO_DIRECTORY"
sed -i "s/tag: .*/tag: $COMMIT/" "$ISTIO_DIRECTORY/profile.yaml"
$ISTIOCTL manifest generate -f profile.yaml -f profile-overlay.yaml \
  --set components.cni.enabled=true \
  --set components.cni.namespace=kube-system > dump.yaml
./split-istio-packages -f dump.yaml
sed -i -e 's/[[:space:]]\+$//' -e '${/^$/d;}' \
  crd.yaml install.yaml cluster-local-gateway.yaml
mv $ISTIO_DIRECTORY/crd.yaml $ISTIO_DIRECTORY/istio-crds/base/
mv $ISTIO_DIRECTORY/install.yaml $ISTIO_DIRECTORY/istio-install/base/
mv $ISTIO_DIRECTORY/cluster-local-gateway.yaml $ISTIO_DIRECTORY/cluster-local-gateway/base/
rm dump.yaml
$ISTIOCTL manifest generate -f profile.yaml -f profile-overlay.yaml \
  --set components.cni.enabled=true \
  --set components.ztunnel.enabled=true > dump-ztunnel.yaml
./split-istio-packages -f dump-ztunnel.yaml
sed -i -e 's/[[:space:]]\+$//' -e '${/^$/d;}' \
  crd.yaml install.yaml cluster-local-gateway.yaml ztunnel.yaml
mv $ISTIO_DIRECTORY/ztunnel.yaml $ISTIO_DIRECTORY/istio-install/components/ambient-mode/
rm dump-ztunnel.yaml crd.yaml install.yaml cluster-local-gateway.yaml
sed -i "s/\"tag\": \".*\"/\"tag\": \"$COMMIT\"/" "$ISTIO_DIRECTORY/istio-install/base/patches/istio-sidecar-injector-patch.yaml"
# Normalize all remaining Istio version references from PREVIOUS_COMMIT to COMMIT.
# This catches any version strings that istioctl generates using the previous release
# (e.g. image tags, helm chart labels). Update PREVIOUS_COMMIT when needed.
find "$ISTIO_DIRECTORY" -name "*.yaml" \
  ! -path "$ISTIO_DIRECTORY/helm/Chart.yaml" -exec sed -i \
  -e "s/${PREVIOUS_COMMIT}/$COMMIT/g" {} +
update_helm_chart_application_version \
  "$ISTIO_DIRECTORY/helm/Chart.yaml" "$COMMIT"

normalize_generated_yaml() {
  sed \
    -e 's/[[:space:]]\+$//' \
    -e '${/^$/d;}'
}

render_helm_manifest_payload() {
  local source_path=$1

  {
    printf "# Generated by: kustomize build %s\n" "${source_path#"$MANIFESTS_DIRECTORY/"}"
    printf "# Refresh with scripts/synchronize-istio-manifests.sh for Istio %s.\n" "$COMMIT"
    kustomize build "$source_path"
  } | normalize_generated_yaml
}

render_helm_manifest() {
  local source_path=$1
  local output_file=$2

  write_generated_file_atomically \
    "$output_file" render_helm_manifest_payload "$source_path"
}

# Select whole documents from a multi-document manifest stream by their top
# level kind. Documents are matched by their kind rather than by position, and
# their lines are reproduced unchanged; only the separators between the selected
# documents are rewritten as a plain "---".
select_manifest_documents() {
  local selection=$1
  local kind=$2

  awk -v selection="$selection" -v kind="$kind" '
    function flush_document(   index_of_line, document_kind, kind_matches) {
      if (line_count == 0) {
        return
      }
      document_kind = ""
      for (index_of_line = 1; index_of_line <= line_count; index_of_line++) {
        if (lines[index_of_line] ~ /^kind:[[:space:]]/) {
          document_kind = lines[index_of_line]
          sub(/^kind:[[:space:]]+/, "", document_kind)
          sub(/[[:space:]\r]+$/, "", document_kind)
          break
        }
      }
      kind_matches = (document_kind == kind)
      if ((selection == "only") == kind_matches) {
        if (emitted_documents > 0) {
          print "---"
        }
        for (index_of_line = 1; index_of_line <= line_count; index_of_line++) {
          print lines[index_of_line]
        }
        emitted_documents++
      }
      line_count = 0
    }
    # A document separator is --- alone on a line, optionally followed by a
    # comment, and tolerant of trailing whitespace or a carriage return. YAML
    # requires a blank before a comment, so ---#text is content, not a separator.
    /^---([[:space:]]+#.*)?[[:space:]]*\r?$/ { flush_document(); next }
    { lines[++line_count] = $0 }
    END { flush_document() }
  '
}

render_selected_documents_payload() {
  local source_path=$1
  local selection=$2
  local kind=$3
  local description

  if [[ "$selection" == "only" ]]; then
    description="$kind documents only"
  else
    description="documents other than $kind"
  fi

  {
    printf "# Generated by: kustomize build %s, %s\n" \
      "${source_path#"$MANIFESTS_DIRECTORY/"}" "$description"
    printf "# Refresh with scripts/synchronize-istio-manifests.sh for Istio %s.\n" "$COMMIT"
    kustomize build "$source_path" | select_manifest_documents "$selection" "$kind"
  } | normalize_generated_yaml
}

render_selected_documents_manifest() {
  local source_path=$1
  local selection=$2
  local kind=$3
  local output_file=$4

  write_generated_file_atomically \
    "$output_file" render_selected_documents_payload \
    "$source_path" "$selection" "$kind"
}

render_helm_manifest "$ISTIO_DIRECTORY/istio-crds/base" \
  "$HELM_MANIFESTS_DIRECTORY/crds.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/istio-install/base" \
  "$HELM_MANIFESTS_DIRECTORY/install-base.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/istio-install/overlays/oauth2-proxy" \
  "$HELM_MANIFESTS_DIRECTORY/install-oauth2-proxy.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/istio-install/overlays/gke" \
  "$HELM_MANIFESTS_DIRECTORY/install-gke.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/cluster-local-gateway/base" \
  "$HELM_MANIFESTS_DIRECTORY/cluster-local-gateway.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/cluster-local-gateway/overlays/m2m-auth" \
  "$HELM_MANIFESTS_DIRECTORY/cluster-local-gateway-m2m-auth.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/kubeflow-istio-resources/base" \
  "$HELM_MANIFESTS_DIRECTORY/kubeflow-istio-resources.yaml"
render_selected_documents_manifest "$ISTIO_DIRECTORY/istio-namespace/base" \
  only Namespace "$HELM_MANIFESTS_DIRECTORY/namespaces.yaml"
render_selected_documents_manifest "$ISTIO_DIRECTORY/istio-namespace/base" \
  except Namespace "$HELM_MANIFESTS_DIRECTORY/networkpolicies.yaml"
if ! grep -q "^kind: Namespace$" "$HELM_MANIFESTS_DIRECTORY/namespaces.yaml"; then
  echo "No Namespace document was rendered into namespaces.yaml" >&2
  exit 1
fi
if grep -q "^kind: Namespace$" "$HELM_MANIFESTS_DIRECTORY/networkpolicies.yaml"; then
  echo "A Namespace document leaked into networkpolicies.yaml" >&2
  exit 1
fi
SOURCE_TEXT="\[.*\](https://github.com/${REPOSITORY_NAME}/releases/tag/.*)"
DESTINATION_TEXT="\[$COMMIT\](https://github.com/${REPOSITORY_NAME}/releases/tag/$COMMIT)"
update_readme "$MANIFESTS_DIRECTORY" "$SOURCE_TEXT" "$DESTINATION_TEXT"
commit_changes "$MANIFESTS_DIRECTORY" "Update ${REPOSITORY_NAME} manifests from ${COMMIT}" \
  "README.md" \
  "scripts/synchronize-istio-manifests.sh" \
  "common/${COMPONENT_NAME}"
echo "Synchronization completed successfully."
