apiVersion: v2
name: oauth2-proxy
description: A Helm chart for Kubeflow oauth2-proxy authentication and authorization resources
version: 0.1.0
appVersion: "7.15.4"

keywords:
- authentication
- authorization
- oauth2
- kubeflow
- oauth2-proxy

home: https://github.com/kubeflow/community-distribution

sources:
- https://github.com/kubeflow/community-distribution/tree/master/common/oauth2-proxy
- https://github.com/oauth2-proxy/oauth2-proxy

annotations:
  category: Authentication
  licenses: Apache-2.0
