apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../pipeline/upstream/env/cert-manager/platform-agnostic-multi-user

patches:
- path: patches/pipeline-install-config-securitycontext.yaml
