apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
- service.yaml
- virtual-service.yaml
- authorizationpolicy.yaml



configurations:
- params.yaml


images:
- name: ghcr.io/kubeflow/kubeflow/kfam
  newName: ghcr.io/kubeflow/kubeflow/kfam
  newTag: v1.10.0
labels:
- includeSelectors: true
  pairs:
    kustomize.component: profiles
patches:
- path: patches/kfam.yaml
- path: patches/remove-namespace.yaml
replacements:
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: profiles-kfam
    version: v1
  targets:
  - fieldPaths:
    - spec.http.0.route.0.destination.host
    options:
      delimiter: .
      index: 1
    select:
      group: networking.istio.io
      kind: VirtualService
      name: profiles-kfam
      version: v1alpha3