apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeflow-pipelines-profile-controller
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/name: kubeflow-pipelines
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kubeflow-pipelines-profile-controller
        app.kubernetes.io/component: ml-pipeline
        app.kubernetes.io/name: kubeflow-pipelines
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
      - name: profile-controller
        image: alpine/k8s:1.29.13
        command: ["python", "/hooks/sync.py"]
        env:
        - name: KFP_VERSION
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: appVersion
        - name: AWS_ENDPOINT_URL
          value: http://minio-service:8111
        # The following AWS_* vars can be any value. They are just needed for botocore to work
        # seaweedfs does not need auth or region on the IAM.
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: seaweedfs-admin
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: seaweedfs-admin
              key: secretkey
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        ports:
        - containerPort: 8080
      volumes:
      - name: hooks
        configMap:
          name: kubeflow-pipelines-profile-controller-code
