apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: kubeflow-monitoring-system
  labels:
    dashboards: "grafana"
spec:
  config:
    auth:
      disable_login_form: "false"
    users:
      allow_sign_up: "false"
  deployment:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: grafana
            image: grafana/grafana:10.2.3
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
