apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-operator
  namespace: kubeflow-monitoring-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeflow-grafana-operator
  namespace: kubeflow-monitoring-system
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["grafana.integreatly.org"]
  resources: ["grafanas", "grafanadashboards", "grafanadatasources", "grafanafolders"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeflow-grafana-operator
  namespace: kubeflow-monitoring-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeflow-grafana-operator
subjects:
- kind: ServiceAccount
  name: grafana-operator
  namespace: kubeflow-monitoring-system
