apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow-workspaces

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: ui

images:
- name: workspaces-frontend
  newName: ghcr.io/kubeflow/notebooks/workspaces-frontend
  newTag: v2.0.0-alpha.0
